version: "3.7"

networks:
  escola_lms:
    name: escola_lms
    driver: bridge
services:
  admin:
    image: escolalms/admin
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:1000
  api:
    image: escolalms/api:0.2.8
    ports:
      - "1000:80"
    networks:
      - escola_lms
    volumes:
      - ./docker/supervisor/horizon.conf:/etc/supervisor/custom.d/horizon.conf
      - ./docker/supervisor/scheduler.conf:/etc/supervisor/custom.d/scheduler.conf
      - ./storage:/var/www/html/storage
      - type: bind
        source: ./.env
        target: /var/www/html/.env
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    networks:
      - escola_lms
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
      - TZ=Europe/Warsaw

  redis:
    networks:
      - escola_lms
    image: "redis"
    command: redis-server --requirepass escola_lms
    ports:
      - "6379:6379"

  adminer:
    networks:
      - escola_lms
    image: adminer
    ports:
      - 8078:8080

  mailhog:
    networks:
      - escola_lms
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

