version: "3.7"

networks:
  escola_lms:
    name: escola_lms
    driver: bridge
services:

  proxy:
    image: caddy
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/etc/caddy/certs
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks: 
      - escola_lms
    ports: 
      - "80:80"      
      - "443:443"      


  app:
    image: escolalms/demo:latest
    environment:
      - API_URL=http://api.wellms.localhost
    networks:
      - escola_lms
  admin:
    image: escolalms/admin:latest
    environment:
      - API_URL=http://api.wellms.localhost
    networks:
      - escola_lms
  api:
    image: escolalms/api:latest
    networks:
      - escola_lms
    volumes:
      - ./docker/supervisor/horizon.conf:/etc/supervisor/custom.d/horizon.conf
      - ./docker/supervisor/scheduler.conf:/etc/supervisor/custom.d/scheduler.conf
      - ./storage:/var/www/html/storage
      - type: bind
        source: ./.env
        target: /var/www/html/.env
  postgres:
    image: postgres:12
    networks:
      - escola_lms
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
      - TZ=Europe/Warsaw

  redis:
    networks:
      - escola_lms
    image: "redis"
    command: redis-server --requirepass escola_lms

#  adminer:
#    networks:
#      - escola_lms
#    image: adminer
#    ports:
#      - 8078:8080

  mailhog:
    networks:
      - escola_lms
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
#    ports:
#      - 1025:1025 # smtp server
#      - 8025:8025 # web ui

